In [7]:
import pandas as pd

In [8]:
cocktails_file = "Resources/cocktails.csv"
cities_file = "Resources/uscities.csv"

In [10]:
cocktails = pd.read_csv(cocktails_file)
cities = pd.read_csv(cities_file)

In [11]:
cocktails.head()

,Cocktail Name,Bartender,Bar/Company,Location,Ingredients,Garnish,Glassware,Preparation,Notes
0,Flor de Amaras,Kelly McCarthy,NaN,Boston,"1.5 oz Mezcal, 1 oz Hibiscus Simple Syrup*, .5...",Marigold Petals,NaN,*Hibiscus Simple Syrup:\n1:1 w/ a cup of dried...,NaN
1,The Happy Place,Elizabeth Montana,Forgery & Verso,San Francisco,"2 oz Junipero Gin, .75 oz House-made Cranberry...","Dehydrated Lemon Wheel, Sprig of Rosemary",NaN,*House-made Cranberry syrup: \n-- 2 cups Fresh...,Junipero Gin 20th Anniversary Signature Cocktail
2,Bon Voyage Pisco Punch,Jon Morales,NaN,San Francisco,"1500 ml BarSol Selecto Italia Pisco, 750 ml Le...",NaN,Punch Bowl,*Pineapple Gomme: \nMix equal parts (1.5 cups)...,NaN
3,Still Life of a Pineapple,Daniel Braganca,Backbar,Somerville,"1.5 oz BarSol Primero Quebranta Pisco, .75 oz ...",NaN,NaN,*Pineapple Syrup:\n<em>Equal parts pineapple b...,NaN
4,The Bittered Valley,Nik Virrey,NaN,Seattle,"1.25 oz Luxardo Maraschino Liqueur, 4 drops Ac...",NaN,NaN,"1st glass ingredients:\nLuxardo Maraschino, Ac...",NaN

In [33]:
cities

,city,city_ascii,state_id,state_name,county_fips,county_name,county_fips_all,county_name_all,lat,lng,population,density,source,military,incorporated,timezone,ranking,zips,id
0,South Creek,South Creek,WA,Washington,53053,Pierce,53053,Pierce,46.9994,-122.3921,2500.0,125.0,polygon,False,True,America/Los_Angeles,3,98580 98387 98338,1840116412
1,Roslyn,Roslyn,WA,Washington,53037,Kittitas,53037,Kittitas,47.2507,-121.0989,947.0,84.0,polygon,False,True,America/Los_Angeles,3,98941 98068 98925,1840097718
2,Sprague,Sprague,WA,Washington,53043,Lincoln,53043,Lincoln,47.3048,-117.9713,441.0,163.0,polygon,False,True,America/Los_Angeles,3,99032,1840096300
3,Gig Harbor,Gig Harbor,WA,Washington,53053,Pierce,53053,Pierce,47.3352,-122.5968,9507.0,622.0,polygon,False,True,America/Los_Angeles,3,98332 98335,1840097082
4,Lake Cassidy,Lake Cassidy,WA,Washington,53061,Snohomish,53061,Snohomish,48.0639,-122.0920,3591.0,131.0,polygon,False,True,America/Los_Angeles,3,98223 98258 98270,1840116371
5,Tenino,Tenino,WA,Washington,53067,Thurston,53067,Thurston,46.8537,-122.8607,1830.0,491.0,polygon,False,True,America/Los_Angeles,3,98589,1840097290
6,Jamestown,Jamestown,WA,Washington,53009,Clallam,53009,Clallam,48.1229,-123.0911,289.0,191.0,polygon,False,False,America/Los_Angeles,3,98382,1840116876
7,Three Lakes,Three Lakes,WA,Washington,53061,Snohomish,53061,Snohomish,47.9420,-121.9924,3390.0,112.0,polygon,False,False,America/Los_Angeles,3,98290,1840113264
8,Curlew Lake,Curlew Lake,WA,Washington,53019,Ferry,53019,Ferry,48.7311,-118.6663,573.0,50.0,polygon,False,True,America/Los_Angeles,3,99166,1840118428
9,Chain Lake,Chain Lake,WA,Washington,53061,Snohomish,53061,Snohomish,47.9038,-121.9861,4280.0,156.0,polygon,False,True,America/Los_Angeles,3,98290,1840116340
10,Pateros,Pateros,WA,Washington,53047,Okanogan,53047,Okanogan,48.0536,-119.8994,701.0,536.0,polygon,False,True,America/Los_Angeles,3,98846,1840097686
11,Rosburg,Rosburg,WA,Washington,53069,Wahkiakum,53069,Wahkiakum,46.3076,-123.6344,385.0,6.0,polygon,False,False,America/Los_Angeles,3,98643,1840116404
12,Parkland,Parkland,WA,Washington,53053,Pierce,53053,Pierce,47.1417,-122.4376,37019.0,1653.0,polygon,False,False,America/Los_Angeles,3,98444 98445 98447 98448,1840113004
13,Birch Bay,Birch Bay,WA,Washington,53073,Whatcom,53073,Whatcom,48.9230,-122.7543,8642.0,208.0,polygon,False,False,America/Los_Angeles,3,98230,1840111899
14,Ashford,Ashford,WA,Washington,53053,Pierce,53053,Pierce,46.7537,-122.0113,162.0,30.0,polygon,False,False,America/Los_Angeles,3,98304,1840111824
15,Navy Yard City,Navy Yard City,WA,Washington,53035,Kitsap,53035,Kitsap,47.5508,-122.6655,3154.0,1978.0,polygon,False,False,America/Los_Angeles,3,98312,1840112893
16,Omak,Omak,WA,Washington,53047,Okanogan,53047,Okanogan,48.4228,-119.5159,8130.0,478.0,polygon,False,True,America/Los_Angeles,3,98841,1840097677
17,Farmington,Farmington,WA,Washington,53075,Whitman,53075,Whitman,47.0887,-117.0464,154.0,164.0,polygon,False,True,America/Los_Angeles,3,99128,1840097850
18,Buckley,Buckley,WA,Washington,53053,Pierce,53053,Pierce,47.1615,-122.0200,4819.0,482.0,polygon,False,True,America/Los_Angeles,3,98321,1840097435
19,Cathcart,Cathcart,WA,Washington,53061,Snohomish,53061,Snohomish,47.8525,-122.1058,2506.0,250.0,polygon,False,False,America/Los_Angeles,3,98296,1840112035
20,Poulsbo,Poulsbo,WA,Washington,53035,Kitsap,53035,Kitsap,47.7417,-122.6408,10670.0,869.0,polygon,False,True,America/Los_Angeles,3,98370,1840096283
21,Anacortes,Anacortes,WA,Washington,53057,Skagit,53057,Skagit,48.4878,-122.6292,17955.0,559.0,polygon,False,True,America/Los_Angeles,3,98221,1840096971
22,Maplewood,Maplewood,WA,Washington,53053,Pierce,53053,Pierce,47.3715,-122.5689,5340.0,248.0,polygon,False,False,America/Los_Angeles,3,98332,1840116381
23,Creston,Creston,WA,Washington,53043,Lincoln,53043,Lincoln,47.7595,-118.5200,226.0,212.0,polygon,False,True,America/Los_Angeles,3,99117,1840096226
24,Rockford,Rockford,WA,Washington,53063,Spokane,53063,Spokane,47.4513,-117.1307,477.0,271.0,polygon,False,True,America/Los_Angeles,3,99030,1840096289
25,Wishram,Wishram,WA,Washington,53039,Klickitat,53039,Klickitat,45.6599,-120.9698,438.0,131.0,polygon,False,False,America/Los_Angeles,3,98673,1840113455
26,Centralia,Centralia,WA,Washington,53041,Lewis,53041,Lewis,46.7225,-122.9695,41643.0,883.0,polygon,False,True,America/Los_Angeles,3,98531,1840096216
27,South Hill,South Hill,WA,Washington,53053,Pierce,53053,Pierce,47.1203,-122.2848,56379.0,1185.0,polygon,False,False,America/Los_Angeles,3,98375 98374 98373,1840112763
28,Longview Heights,Longview Heights,WA,Washington,53015,Cowlitz,53015,Cowlitz,46.1796,-122.9577,3678.0,337.0,polygon,False,False,America/Los_Angeles,3,98632,1840112166
29,Erlands Point-Kitsap Lake,Erlands Point-Kitsap Lake,WA,Washington,53035,Kitsap,53035,Kitsap,47.5973,-122.7021,2973.0,655.0,polygon,False,True,America/Los_Angeles,3,98312,1840112126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28859,Lemmon,Lemmon,SD,South Dakota,46105,Perkins,46105,Perkins,45.9385,-102.1589,1213.0,451.0,polygon,False,True,America/Denver,3,57638,1840081819
28860,Grenville,Grenville,SD,South Dakota,46037,Day,46037,Day,45.4667,-97.3900,55.0,89.0,polygon,False,True,America/Chicago,3,57239,1840081776
28861,Hetland,Hetland,SD,South Dakota,46077,Kingsbury,46077,Kingsbury,44.3771,-97.2345,48.0,162.0,polygon,False,True,America/Chicago,3,57212,1840082267
28862,Claire City,Claire City,SD,South Dakota,46109,Roberts,46109,Roberts,45.8566,-97.1035,77.0,162.0,polygon,False,True,America/Chicago,3,57224,1840081712
28863,Goodwill,Goodwill,SD,South Dakota,46109,Roberts,46109,Roberts,45.5673,-97.0612,757.0,387.0,polygon,False,False,America/Chicago,3,57262,1840115966
28864,Forestburg,Forestburg,SD,South Dakota,46111,Sanborn,46111,Sanborn,44.0213,-98.1032,128.0,93.0,polygon,False,False,America/Chicago,3,57314,1840115964
28865,Mellette,Mellette,SD,South Dakota,46115,Spink,46115,Spink,45.1544,-98.4983,214.0,322.0,polygon,False,True,America/Chicago,3,57461,1840081847
28866,Castlewood,Castlewood,SD,South Dakota,46057,Hamlin,46057,Hamlin,44.7242,-97.0309,626.0,210.0,polygon,False,True,America/Chicago,3,57223,1840082250
28867,Chelsea,Chelsea,SD,South Dakota,46049,Faulk,46049,Faulk,45.1676,-98.7434,27.0,32.0,polygon,False,True,America/Chicago,3,57465,1840081710
28868,Tripp,Tripp,SD,South Dakota,46067,Hutchinson,46067,Hutchinson,43.2255,-97.9658,632.0,411.0,polygon,False,True,America/Chicago,3,57376,1840081965
28869,Seneca,Seneca,SD,South Dakota,46049,Faulk,46049,Faulk,45.0608,-99.5092,37.0,34.0,polygon,False,True,America/Chicago,3,57473,1840082295
28870,Dimock,Dimock,SD,South Dakota,46067,Hutchinson,46067,Hutchinson,43.4763,-97.9884,131.0,309.0,polygon,False,True,America/Chicago,3,57331,1840081734
28871,Akaska,Akaska,SD,South Dakota,46129,Walworth,46129,Walworth,45.3310,-100.1209,47.0,29.0,polygon,False,True,America/Chicago,3,57420,1840082243
28872,Hillsview,Hillsview,SD,South Dakota,46089,McPherson,46089,McPherson,45.6642,-99.5607,3.0,1.0,polygon,False,True,America/Chicago,3,57437,1840082065
28873,Salem,Salem,SD,South Dakota,46087,McCook,46087,McCook,43.7228,-97.3893,1277.0,394.0,polygon,False,True,America/Chicago,3,57058,1840081927
28874,Huron,Huron,SD,South Dakota,46005,Beadle,46005,Beadle,44.3622,-98.2102,13164.0,532.0,polygon,False,True,America/Chicago,3,57350 57399,1840081802
28875,Edgemont,Edgemont,SD,South Dakota,46047,Fall River,46047,Fall River,43.2983,-103.8271,711.0,287.0,polygon,False,True,America/Denver,3,57735,1840082358
28876,St. Charles,St. Charles,SD,South Dakota,46053,Gregory,46053,Gregory,43.0882,-99.0949,12.0,23.0,polygon,False,False,America/Chicago,3,57571,1840110540
28877,White Rock,White Rock,SD,South Dakota,46109,Roberts,46109,Roberts,45.9248,-96.5760,3.0,0.0,polygon,False,True,America/Chicago,3,57260,1840082005
28878,Lake Norden,Lake Norden,SD,South Dakota,46057,Hamlin,46057,Hamlin,44.5799,-97.2108,476.0,214.0,polygon,False,True,America/Chicago,3,57248,1840081816
28879,Summit,Summit,SD,South Dakota,46109,Roberts,46109,Roberts,45.3056,-97.0391,291.0,205.0,polygon,False,True,America/Chicago,3,57266,1840082345
28880,Colome,Colome,SD,South Dakota,46123,Tripp,46123,Tripp,43.2599,-99.7174,283.0,382.0,polygon,False,True,America/Chicago,3,57528,1840081720
28881,Okreek,Okreek,SD,South Dakota,46121,Todd,46121,Todd,43.3534,-100.3826,379.0,3.0,polygon,False,False,America/Chicago,3,57555 57580 57563,1840115974
28882,Lane,Lane,SD,South Dakota,46073,Jerauld,46073,Jerauld,44.0697,-98.4246,59.0,49.0,polygon,False,True,America/Chicago,3,57358 57382,1840081817
28883,Willow Lake,Willow Lake,SD,South Dakota,46025,Clark,46025,Clark,44.6279,-97.6387,240.0,248.0,polygon,False,True,America/Chicago,3,57278,1840082007
28884,Montrose,Montrose,SD,South Dakota,46087,McCook,46087,McCook,43.7002,-97.1843,442.0,414.0,polygon,False,True,America/Chicago,3,57048,1840081860
28885,Spearfish,Spearfish,SD,South Dakota,46081,Lawrence,46081,Lawrence,44.4912,-103.8167,12675.0,272.0,polygon,False,True,America/Denver,3,57783 57799,1840082231
28886,Emery,Emery,SD,South Dakota,46061,Hanson,46061,Hanson,43.6020,-97.6195,455.0,384.0,polygon,False,True,America/Chicago,3,57332,1840081745
28887,Watertown,Watertown,SD,South Dakota,46029,Codington,46029,Codington,44.9094,-97.1532,21837.0,475.0,polygon,False,True,America/Chicago,3,57201,1840081993
28888,Buffalo,Buffalo,SD,South Dakota,46063,Harding,46063,Harding,45.5864,-103.5434,346.0,241.0,polygon,False,True,America/Denver,3,57720,1840081693

In [21]:
loc = cocktails['Location'].unique()
loc = list(loc)
loc

['Boston',
 'San Francisco',
 'Somerville',
 'Seattle',
 'Alameda',
 'Chicago',
 nan,
 'New Orleans',
 'Atlanta',
 'Houston',
 'New York',
 'Philadelphia',
 'Brooklyn',
 'St. Louis',
 'New Zealand',
 'Austin',
 'Dallas',
 'San Diego',
 'Pacifica',
 'Sacramento',
 'Phoenix',
 'Los Gatos',
 'Milwaukee',
 'Washington DC',
 'Chicago, Ill',
 'United Kingdom',
 'Miami',
 'Los Angeles',
 'Austin ',
 'Spain',
 'Anaheim',
 'London',
 'Carlsbad',
 'Westport',
 'Fort Worth',
 'Charleston',
 'Denver',
 'Las Vegas',
 'Portland',
 'Japan',
 'San Luis Obispo',
 'Nashville']

In [24]:
len(loc)
x=range(0,42)

range(0, 42)

In [27]:
city_id = pd.DataFrame({'city':loc})

In [31]:
city_id.index.name = 'id'

In [32]:
city_id.head()

             city
id
0          Boston
1   San Francisco
2      Somerville
3         Seattle
4         Alameda

In [41]:
a = cities['city'].unique()
us_unique = pd.DataFrame({'city':a})

In [57]:
us_unique['city'].value_counts()

Covedale                    1
St. Rose                    1
Flor del Rio                1
Alpaugh                     1
Lisle                       1
                           ..
Manheim                     1
Welch                       1
Shawnee Hills               1
Wrenshall                   1
Otis Orchards-East Farms    1
Name: city, Length: 19387, dtype: int64

In [58]:
city_id = pd.merge(city_id,us_unique,how='inner')
city_id.head()

            city
0         Boston
1  San Francisco
2     Somerville
3        Seattle
4        Alameda

In [59]:
city_id.index.name = 'id'
city_id

               city
id
0            Boston
1     San Francisco
2        Somerville
3           Seattle
4           Alameda
5           Chicago
6       New Orleans
7           Atlanta
8           Houston
9          New York
10     Philadelphia
11         Brooklyn
12        St. Louis
13           Austin
14           Dallas
15        San Diego
16         Pacifica
17       Sacramento
18          Phoenix
19        Los Gatos
20        Milwaukee
21            Miami
22      Los Angeles
23          Anaheim
24           London
25         Carlsbad
26         Westport
27       Fort Worth
28       Charleston
29           Denver
30        Las Vegas
31         Portland
32  San Luis Obispo
33        Nashville

In [55]:
pd.merge()

KeyError: 0             Boston
1      San Francisco
2      San Francisco
3         Somerville
4            Seattle
           ...
682              NaN
683         New York
684          Seattle
685        Nashville
686           Denver
Name: Location, Length: 687, dtype: object